import { Column, Entity, JoinColumn, ManyToOne } from 'typeorm';
import { BaseEntity } from '../../base.entity';
import { Account } from 'src/users/entities/account.entity';
import { Property } from 'src/properties/entities/property.entity';

export enum TenantBalanceLedgerType {
  INITIAL_BALANCE = 'initial_balance',
  AUTO_RENEWAL = 'auto_renewal',
  RENT_PAYMENT = 'rent_payment',
  OB_PAYMENT = 'ob_payment',
  /** Legacy — generated by old two-step payment flow, no longer created. */
  CREDIT_APPLIED = 'credit_applied',
  /** Legacy — generated by old two-step payment flow, no longer created. */
  CREDIT_ADDED = 'credit_added',
  MIGRATION = 'migration',
}

@Entity({ name: 'tenant_balance_ledger' })
export class TenantBalanceLedger extends BaseEntity {
  @Column({ nullable: false, type: 'uuid' })
  tenant_id!: string;

  @Column({ nullable: false, type: 'uuid' })
  landlord_id!: string;

  @Column({ nullable: true, type: 'uuid' })
  property_id!: string | null;

  @Column({
    nullable: false,
    type: 'enum',
    enum: TenantBalanceLedgerType,
  })
  type!: TenantBalanceLedgerType;

  /** Human-readable description shown in the breakdown modal. */
  @Column({ nullable: false, type: 'text' })
  description!: string;

  /**
   * Signed change to the wallet balance for this entry.
   * positive = balance increased (payment received / credit added)
   * negative = balance decreased (charge added)
   */
  @Column({ type: 'decimal', precision: 12, scale: 2, default: 0 })
  balance_change!: number;

  /** Snapshot of wallet balance after this entry. */
  @Column({ type: 'decimal', precision: 12, scale: 2 })
  balance_after!: number;

  /** The entity (rent / renewal_invoice / property_history) that triggered this change. */
  @Column({ nullable: true, type: 'varchar', length: 50 })
  related_entity_type!: string | null;

  @Column({ nullable: true, type: 'uuid' })
  related_entity_id!: string | null;

  @ManyToOne(() => Account, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'tenant_id', referencedColumnName: 'id' })
  tenant!: Account;

  @ManyToOne(() => Account, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'landlord_id', referencedColumnName: 'id' })
  landlord!: Account;

  @ManyToOne(() => Property, { nullable: true, onDelete: 'SET NULL' })
  @JoinColumn({ name: 'property_id', referencedColumnName: 'id' })
  property!: Property | null;
}
