import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Renames every DB identifier carrying the "service_request" name to
 * "maintenance_request":
 *   - tables: service_requests, service_request_status_history, auto_service_requests
 *   - dependent FK columns: chat_messages.service_request_id, notification.service_request_id
 *   - enum types: status, scope, creator_type, status-history previous/new, auto-* status/priority/source
 *   - indexes + FK constraints
 *
 * Backfills two stored-string columns the application reads back:
 *   - property_histories.event_type values prefixed 'service_request_'
 *   - notification.type rows storing the literal 'Service Request'
 *
 * Postgres ALTER TABLE/TYPE RENAME is metadata-only; the migration is fast.
 * down() reverses every rename so we can roll back without data loss.
 */
export class RenameServiceRequestToMaintenanceRequest1795000000000
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    // ── Tables ──────────────────────────────────────────────────────────
    await queryRunner.query(
      `ALTER TABLE "service_requests" RENAME TO "maintenance_requests"`,
    );
    await queryRunner.query(
      `ALTER TABLE "service_request_status_history" RENAME TO "maintenance_request_status_history"`,
    );
    await queryRunner.query(
      `ALTER TABLE "auto_service_requests" RENAME TO "auto_maintenance_requests"`,
    );

    // ── Dependent columns on other tables ───────────────────────────────
    await queryRunner.query(
      `ALTER TABLE "chat_messages" RENAME COLUMN "service_request_id" TO "maintenance_request_id"`,
    );
    await queryRunner.query(
      `ALTER TABLE "notification" RENAME COLUMN "service_request_id" TO "maintenance_request_id"`,
    );
    await queryRunner.query(
      `ALTER TABLE "maintenance_request_status_history" RENAME COLUMN "service_request_id" TO "maintenance_request_id"`,
    );

    // ── Enum types ──────────────────────────────────────────────────────
    await queryRunner.query(
      `ALTER TYPE "public"."service_requests_status_enum" RENAME TO "maintenance_requests_status_enum"`,
    );
    await queryRunner.query(
      `ALTER TYPE "public"."service_request_scope_enum" RENAME TO "maintenance_request_scope_enum"`,
    );
    await queryRunner.query(
      `ALTER TYPE "public"."service_request_creator_type_enum" RENAME TO "maintenance_request_creator_type_enum"`,
    );
    await queryRunner.query(
      `ALTER TYPE "public"."service_request_status_history_previous_status_enum" RENAME TO "maintenance_request_status_history_previous_status_enum"`,
    );
    await queryRunner.query(
      `ALTER TYPE "public"."service_request_status_history_new_status_enum" RENAME TO "maintenance_request_status_history_new_status_enum"`,
    );
    // auto_service_requests has 3 autogenerated enums (status/priority/source).
    await queryRunner.query(
      `ALTER TYPE "public"."auto_service_requests_status_enum" RENAME TO "auto_maintenance_requests_status_enum"`,
    );
    await queryRunner.query(
      `ALTER TYPE "public"."auto_service_requests_priority_enum" RENAME TO "auto_maintenance_requests_priority_enum"`,
    );
    await queryRunner.query(
      `ALTER TYPE "public"."auto_service_requests_source_enum" RENAME TO "auto_maintenance_requests_source_enum"`,
    );

    // ── Indexes ─────────────────────────────────────────────────────────
    await queryRunner.query(
      `ALTER INDEX IF EXISTS "idx_service_requests_property_scope" RENAME TO "idx_maintenance_requests_property_scope"`,
    );
    await queryRunner.query(
      `ALTER INDEX IF EXISTS "idx_service_requests_creator_type" RENAME TO "idx_maintenance_requests_creator_type"`,
    );
    await queryRunner.query(
      `ALTER INDEX IF EXISTS "idx_service_requests_is_urgent" RENAME TO "idx_maintenance_requests_is_urgent"`,
    );
    await queryRunner.query(
      `ALTER INDEX IF EXISTS "idx_service_requests_common_area_id" RENAME TO "idx_maintenance_requests_common_area_id"`,
    );
    await queryRunner.query(
      `ALTER INDEX IF EXISTS "IDX_service_request_status_history_service_request_id" RENAME TO "IDX_maintenance_request_status_history_maintenance_request_id"`,
    );
    await queryRunner.query(
      `ALTER INDEX IF EXISTS "IDX_service_request_status_history_changed_at" RENAME TO "IDX_maintenance_request_status_history_changed_at"`,
    );

    // ── FK constraint names on maintenance_requests ─────────────────────
    await queryRunner.query(
      `ALTER TABLE "maintenance_requests" RENAME CONSTRAINT "fk_service_requests_creator_user" TO "fk_maintenance_requests_creator_user"`,
    );
    await queryRunner.query(
      `ALTER TABLE "maintenance_requests" RENAME CONSTRAINT "fk_service_requests_common_area" TO "fk_maintenance_requests_common_area"`,
    );

    // ── Stored-string backfills ─────────────────────────────────────────
    // property_histories.event_type: 'service_request_*' → 'maintenance_request_*'
    await queryRunner.query(`
      UPDATE "property_histories"
         SET "event_type" = REPLACE("event_type", 'service_request_', 'maintenance_request_')
       WHERE "event_type" IN (
         'service_request_created',
         'service_request_updated',
         'service_request_resolved',
         'service_request_reopened',
         'service_request_closed',
         'service_request_approved'
       )
    `);

    // notification.type is the enum *value* (NotificationType.MAINTENANCE_REQUEST).
    // Use ALTER TYPE ... RENAME VALUE — a free-text UPDATE fails because the
    // target literal isn't a valid enum member yet.
    await queryRunner.query(
      `ALTER TYPE "public"."notification_type_enum" RENAME VALUE 'Service Request' TO 'Maintenance Request'`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // Stored-string backfills (reverse).
    await queryRunner.query(
      `ALTER TYPE "public"."notification_type_enum" RENAME VALUE 'Maintenance Request' TO 'Service Request'`,
    );
    await queryRunner.query(`
      UPDATE "property_histories"
         SET "event_type" = REPLACE("event_type", 'maintenance_request_', 'service_request_')
       WHERE "event_type" IN (
         'maintenance_request_created',
         'maintenance_request_updated',
         'maintenance_request_resolved',
         'maintenance_request_reopened',
         'maintenance_request_closed',
         'maintenance_request_approved'
       )
    `);

    // FK constraint names.
    await queryRunner.query(
      `ALTER TABLE "maintenance_requests" RENAME CONSTRAINT "fk_maintenance_requests_common_area" TO "fk_service_requests_common_area"`,
    );
    await queryRunner.query(
      `ALTER TABLE "maintenance_requests" RENAME CONSTRAINT "fk_maintenance_requests_creator_user" TO "fk_service_requests_creator_user"`,
    );

    // Indexes.
    await queryRunner.query(
      `ALTER INDEX IF EXISTS "IDX_maintenance_request_status_history_changed_at" RENAME TO "IDX_service_request_status_history_changed_at"`,
    );
    await queryRunner.query(
      `ALTER INDEX IF EXISTS "IDX_maintenance_request_status_history_maintenance_request_id" RENAME TO "IDX_service_request_status_history_service_request_id"`,
    );
    await queryRunner.query(
      `ALTER INDEX IF EXISTS "idx_maintenance_requests_common_area_id" RENAME TO "idx_service_requests_common_area_id"`,
    );
    await queryRunner.query(
      `ALTER INDEX IF EXISTS "idx_maintenance_requests_is_urgent" RENAME TO "idx_service_requests_is_urgent"`,
    );
    await queryRunner.query(
      `ALTER INDEX IF EXISTS "idx_maintenance_requests_creator_type" RENAME TO "idx_service_requests_creator_type"`,
    );
    await queryRunner.query(
      `ALTER INDEX IF EXISTS "idx_maintenance_requests_property_scope" RENAME TO "idx_service_requests_property_scope"`,
    );

    // Enum types.
    await queryRunner.query(
      `ALTER TYPE "public"."auto_maintenance_requests_source_enum" RENAME TO "auto_service_requests_source_enum"`,
    );
    await queryRunner.query(
      `ALTER TYPE "public"."auto_maintenance_requests_priority_enum" RENAME TO "auto_service_requests_priority_enum"`,
    );
    await queryRunner.query(
      `ALTER TYPE "public"."auto_maintenance_requests_status_enum" RENAME TO "auto_service_requests_status_enum"`,
    );
    await queryRunner.query(
      `ALTER TYPE "public"."maintenance_request_status_history_new_status_enum" RENAME TO "service_request_status_history_new_status_enum"`,
    );
    await queryRunner.query(
      `ALTER TYPE "public"."maintenance_request_status_history_previous_status_enum" RENAME TO "service_request_status_history_previous_status_enum"`,
    );
    await queryRunner.query(
      `ALTER TYPE "public"."maintenance_request_creator_type_enum" RENAME TO "service_request_creator_type_enum"`,
    );
    await queryRunner.query(
      `ALTER TYPE "public"."maintenance_request_scope_enum" RENAME TO "service_request_scope_enum"`,
    );
    await queryRunner.query(
      `ALTER TYPE "public"."maintenance_requests_status_enum" RENAME TO "service_requests_status_enum"`,
    );

    // Dependent columns.
    await queryRunner.query(
      `ALTER TABLE "maintenance_request_status_history" RENAME COLUMN "maintenance_request_id" TO "service_request_id"`,
    );
    await queryRunner.query(
      `ALTER TABLE "notification" RENAME COLUMN "maintenance_request_id" TO "service_request_id"`,
    );
    await queryRunner.query(
      `ALTER TABLE "chat_messages" RENAME COLUMN "maintenance_request_id" TO "service_request_id"`,
    );

    // Tables.
    await queryRunner.query(
      `ALTER TABLE "auto_maintenance_requests" RENAME TO "auto_service_requests"`,
    );
    await queryRunner.query(
      `ALTER TABLE "maintenance_request_status_history" RENAME TO "service_request_status_history"`,
    );
    await queryRunner.query(
      `ALTER TABLE "maintenance_requests" RENAME TO "service_requests"`,
    );
  }
}
