import {
  Column,
  Entity,
  Index,
  JoinColumn,
  ManyToOne,
  OneToMany,
} from 'typeorm';
import { BaseEntity } from '../../base.entity';
import { PropertyTenant } from '../../properties/entities/property-tenants.entity';
import { Property } from '../../properties/entities/property.entity';
import { Account } from '../../users/entities/account.entity';
import { RenewalInvoice } from '../../tenancies/entities/renewal-invoice.entity';
import { FeeKind } from '../../common/billing/fees';
import { PaymentPlanInstallment } from './payment-plan-installment.entity';

export enum PaymentPlanScope {
  TENANCY = 'tenancy',
  CHARGE = 'charge',
  /** Wallet-backed Outstanding-Balance / ad-hoc plan (multi-source, FIFO). */
  OB = 'ob',
}

export enum PaymentPlanSourceType {
  /** Type A — a current-period fee carved out of the renewal invoice. */
  RENEWAL_INVOICE_FEE = 'renewal_invoice_fee',
  /** Type B — wallet-backed outstanding balance (one or more sources). */
  OUTSTANDING_BALANCE = 'outstanding_balance',
  /** Type B — a single ad-hoc invoice. */
  AD_HOC_INVOICE = 'ad_hoc_invoice',
}

export enum PaymentPlanStatus {
  ACTIVE = 'active',
  COMPLETED = 'completed',
  CANCELLED = 'cancelled',
}

export enum PaymentPlanType {
  EQUAL = 'equal',
  CUSTOM = 'custom',
}

@Entity({ name: 'payment_plans' })
@Index(['property_tenant_id'])
@Index(['property_id'])
@Index(['tenant_id'])
@Index(['renewal_invoice_id'])
@Index(['status'])
export class PaymentPlan extends BaseEntity {
  @Column({ type: 'uuid' })
  property_tenant_id: string;

  @ManyToOne(() => PropertyTenant, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'property_tenant_id' })
  propertyTenant: PropertyTenant;

  @Column({ type: 'uuid' })
  property_id: string;

  @ManyToOne(() => Property, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'property_id' })
  property: Property;

  @Column({ type: 'uuid' })
  tenant_id: string;

  @ManyToOne(() => Account, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'tenant_id' })
  tenant: Account;

  /**
   * The renewal invoice this plan applies to. Nullable because the parent
   * invoice may be regenerated by the cron between plan creation and
   * installment settlement; the plan itself still stands.
   */
  @Column({ type: 'uuid', nullable: true })
  renewal_invoice_id: string | null;

  @ManyToOne(() => RenewalInvoice, { onDelete: 'SET NULL', nullable: true })
  @JoinColumn({ name: 'renewal_invoice_id' })
  renewalInvoice: RenewalInvoice | null;

  @Column({ type: 'varchar', length: 20, default: PaymentPlanScope.CHARGE })
  scope: PaymentPlanScope;

  /** Landlord-facing label: "Entire Tenancy", "Service Charge", etc. */
  @Column({ type: 'varchar', length: 255 })
  charge_name: string;

  /**
   * For charge-scope plans, the Fee.kind this plan carves out. Needed to
   * locate the matching entry in renewal_invoice.fee_breakdown when the
   * plan is created (and restore it on cancel).
   */
  @Column({ type: 'varchar', length: 20, nullable: true })
  charge_fee_kind: FeeKind | null;

  /** For kind:'other' fees, disambiguates between multiple "other" entries. */
  @Column({ type: 'varchar', length: 255, nullable: true })
  charge_external_id: string | null;

  /**
   * Which debt space this plan settles. renewal_invoice_fee (Type A) = a
   * current-period fee carved from the invoice; outstanding_balance /
   * ad_hoc_invoice (Type B) = wallet-backed debt. The durable successor to the
   * derived isInvoiceFeeChargePlan predicate.
   */
  @Column({
    type: 'varchar',
    length: 30,
    default: PaymentPlanSourceType.RENEWAL_INVOICE_FEE,
  })
  source_type: PaymentPlanSourceType;

  /**
   * Set when source_type = 'ad_hoc_invoice': the specific ad-hoc invoice this
   * plan settles. (Plain uuid FK — the DB foreign key lives in the migration;
   * kept relation-free to avoid a payment_plans ↔ ad_hoc_invoices import cycle.)
   */
  @Column({ type: 'uuid', nullable: true })
  ad_hoc_invoice_id: string | null;

  @Column({ type: 'decimal', precision: 12, scale: 2 })
  total_amount: number;

  @Column({ type: 'varchar', length: 10, default: PaymentPlanType.EQUAL })
  plan_type: PaymentPlanType;

  @Column({ type: 'varchar', length: 20, default: PaymentPlanStatus.ACTIVE })
  status: PaymentPlanStatus;

  @Column({ type: 'uuid', nullable: true })
  created_by_user_id: string | null;

  @OneToMany(() => PaymentPlanInstallment, (inst) => inst.plan, {
    cascade: true,
  })
  installments: PaymentPlanInstallment[];
}
