export enum NotificationType {
  SERVICE_REQUEST = 'Service Request',
  NOTICE_AGREEMENT = 'Notice Agreement',
  RENT_CREATED = 'Rent Created',
  USER_ADDED_TO_PROPERTY = 'User Added to Property',
  USER_SIGNED_UP = 'User Signed Up',
  LEASE_SIGNED = 'Lease Signed',
  PROPERTY_CREATED = 'Property Created',
  KYC_SUBMITTED = 'KYC Submitted',
  TENANT_ATTACHED = 'Tenant Attached',
  TENANCY_ENDED = 'Tenancy Ended',
  OFFER_LETTER_SENT = 'Offer Letter Sent',
  OFFER_LETTER_ACCEPTED = 'Offer Letter Accepted',
  OFFER_LETTER_REJECTED = 'Offer Letter Rejected',
}
